### ISSUE TITLE
Multiple classes?

### ISSUE THREAD

**Issue by lukepass** [stimulus-components/stimulus-scroll-reveal#1]
Hello, I tried using multiple classes (separated by a space) with the controller but it doesn't seem to work:

```
<div
    data-controller="scroll-reveal"
    data-scroll-reveal-class-value="animate__animated animate__fadeIn"
    >
    <p data-scroll-reveal-target="item" class="reveal">With custom</p>
    <p data-scroll-reveal-target="item" class="reveal">options!</p>
</div>
```

Is there a workaround for this?

Thanks.

**Comment by guillaumebriday** [comment]
Great idea! Done in https://github.com/stimulus-components/stimulus-scroll-reveal/releases/tag/v3.2.0
