### ISSUE TITLE
Please support for toggle class

### ISSUE THREAD

**Issue by pasqualepalmaccio** [stimulus-components/stimulus-scroll-reveal#2]
Hi,
I am testing this component but I realized that there is a missing option for the behavior of the class. In the code, the 'add' method was used which is in line with the domain of the 'scroll-reveal' component, but in some cases, it is necessary for the object class of 'reveal' to be removed when it exits the field of view of the section controlled by the component.

**Comment by pasqualepalmaccio** [comment]
I have implemented an effective solution to enable the toggle of the class by transforming 'scroll-reveal' into 'scroll-trigger'. 
Solution:

`export default class ScrollTrigger extends ScrollReveal {
    static values = {
        toggle: Boolean
    }

    connect() {
        super.connect()
        this.toggle = this.toggleValue || this.defaultOptions.toggle;
    }

    /**
     * Metodo custom per fare il toggle della classe
     * @param entries
     * @param observer
     */
    intersectionObserverCallback(entries, observer) {

        entries.forEach((s) => {

            if (s.intersectionRatio > this.threshold) {
                const e = s.target;
                e.classList.add(this.class), e.dataset.delay && (e.style.transitionDelay = e.dataset.delay);
            }
            if (this.intersectionObserverOptions.toggle && (s.intersectionRatio < this.threshold || s.intersectionRatio === 0)) {
                const e = s.target;
                e.classList.remove(this.class), e.dataset.delay && (e.style.transitionDelay = e.dataset.delay);
            }
        });
    }

    get intersectionObserverOptions() {
        return {
            threshold: this.threshold,
            rootMargin: this.rootMargin,
            toggle: this.toggle
        };
    }

    // You can override this getter to set your default options here.
    get defaultOptions() {
        return {
            class: 'active',
            threshold: 0.5,
            rootMargin: '100px',
            toggle: false
        }
    }
}`

You can use [ data-scroll-reveal-toggle-value="true" ] option to enable toggle of reveal class like this:

`<section  data-controller="scroll-reveal" data-scroll-reveal-class-value="active" data-scroll-reveal-toggle-value="true" data-scroll-reveal-target="item" class=""></section>`

**Comment by pasqualepalmaccio** [comment]
A better version of intersectionObserverCallback method below :

`intersectionObserverCallback(entries, observer) {

        entries.forEach((s) => {

            if (s.intersectionRatio > this.threshold) {
                const e = s.target;
                e.classList.add(this.class), e.dataset.delay && (e.style.transitionDelay = e.dataset.delay);
                const event_start = new CustomEvent('SCROLL_TRIGGER_START', {detail: {target: e}});
                window.dispatchEvent(event_start);
                if(!this.intersectionObserverOptions.toggle){
                    observer.unobserve(e);
                }

            }
            if (this.intersectionObserverOptions.toggle && (s.intersectionRatio < this.threshold || s.intersectionRatio === 0)) {
                const e = s.target;
                e.classList.remove(this.class), e.dataset.delay && (e.style.transitionDelay = e.dataset.delay);
                const event_end = new CustomEvent('SCROLL_TRIGGER_END', {detail: {target: e}});
                window.dispatchEvent(event_end);
            }
        });
    }`

In this version the observer dispatch a custom event that can be listened to by a listener, which is very useful for hooking animations and transitions with JavaScript libraries like anime.js. 
In this code snippet:

`if(!this.intersectionObserverOptions.toggle){
                    observer.unobserve(e);
                }`

 I restore the correct functionality of the scroll-reveal by unhooking the observer from the target if the toggle option is false.

**Comment by elalemanyo** [comment]
@pasqualepalmaccio Thanks for your idea and your code, it's just what I was looking for.
I have allowed myself to use it to open a [pull request](https://github.com/stimulus-components/stimulus-scroll-reveal/pull/4), hope you don't mind.

Thanks!
